### PR TITLE
fix(Validation/EmailMultiple): set HTML5 mode to the email constraint

### PR DESCRIPTION
**Pull request by coppee**

### CODE REVIEW

**Comment by coppee** [comment]
@dameert Do yo know why I have this "old" commits (#71 - #74), already in master, with this PR ? Thanks.

**Comment by dameert** [comment]
You are merging develop into master. Are they really present (on mobile did not check)

**Comment by dameert** [comment]
Ok I checked. Indeed but the commit hash is different in master than the commit hash used in here. I think it's because of the fact that we rebase into master, we should probably merge so that commit hashes don't change :/ my bad!

**Comment by dameert** [comment]
This might be the reason why gitflow goes from develop to release branch to master!

**Comment by coppee** [comment]
Hey @dameert, it's me again. In fact I can't resolve conflict in develop branch as a protected branch. I can do that in local but then I'm stuck (Push develop to ems/develop was rejected by remote) And it's logic... I need to create a another branch with the resolve and merge in ems/develop ? Seems weird or I miss something...

**Comment by dameert** [comment]
Resolve the conflict, add it as a new commit to your branch. Then pr to the ems/develop branch.

**Comment by dameert** [comment]
So we should do a merge, not a rebase!

**Pull request merged**
